[package]
name = "orloglausa-io"
version = "0.1.0"
authors = ["A.W. Stanley <aws@orloglausa.net>"]
edition = "2018"

[features]
# Default
default = ["binary-rw"]

# Stnadard Read/Write
standard-rw = []

# Binary Read/Write
binary-rw = []